- name: clean-workers
  hosts: workers
  gather_facts: true
  become: true
  become_user: root
  roles:
    - role: clean
      tags: ['never', 'workers']

- name: clean-master
  hosts: master
  gather_facts: true
  become: true
  become_user: root
  roles:
    - role: clean
      tags: ['never', 'master']
