- name: Check for executible k3s binary
  stat: 
    path: /usr/local/bin/k3s
  register: p

- name: Download k3s
  get_url:
    url: "{{ k3s_download_url }}"
    dest: "/usr/local/bin/k3s"
    mode: '0755'
  when: p.stat.exists == false

- name: create k3s systemd service
  template:
    src: ../templates/{{ item }}.j2
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - k3s.service
    - k3s.service.env

- name: Enable and start k3s
  service:
    name: k3s
    state: started
    daemon_reload: yes
    enabled: yes

# - name: Run join command
#   shell:
#     cmd: "k3s agent --server https://{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}:6443 --token {{ node_token.stdout }}"

# - debug:
#     msg: "k3s agent --server https://{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}:6443 --token {{ node_token.stdout }}"