{
 "title": "Kubernetes Core Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Pod / Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container - Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{pod=~\".+\"}) by (container, pod) / (sum(container_spec_memory_limit_bytes) by (pod, container) > 0)) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU CFS Throttled Periods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "% Thottled" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total[5m]))by (pod, container)/sum(rate(container_cpu_cfs_periods_total[5m]))by (pod, container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Swap - Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{container=~\".+\"}) by (pod, container)"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Node - Resource Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores) by (node) / sum(kube_node_status_allocatable_cpu_cores) by (node)) * 100",
     "legendFormat": "{{node}} (CPU)"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes) by (node) / sum(kube_node_status_allocatable_memory_bytes) by (node)) * 100",
     "legendFormat": "{{node}} (RAM)"
    },
    {
     "expr": "((node_filesystem_size_bytes-node_filesystem_free_bytes)/node_filesystem_size_bytes) * 100",
     "legendFormat": "{{kubernetes_node}} (Disk)"
    }
   ]
  },
  {
   "title": "Total Swap - Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes) by (kubernetes_node)"
    }
   ]
  },
  {
   "title": "Rx + Tx Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "# of Packets" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total[5m])) by (kubernetes_io_hostname, interface)\n",
     "legendFormat": "Rx-{{kubernetes_io_hostname}}-{{interface}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total[5m])) by (kubernetes_io_hostname, interface)\n",
     "legendFormat": "Tx-{{kubernetes_io_hostname}}-{{interface}}"
    }
   ]
  },
  {
   "title": "Nodes with  Incorrect Clockspeed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Max Frequncy" }
   ],
   "targets": [
    {
     "expr": "(node_cpu_frequency_max_hertz / 1e9) != 2",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "OOM Kills",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Terminations / hour" }
   ],
   "targets": [
    {
     "expr": "sum (delta(node_vmstat_oom_kill[1h])) by (kubernetes_node)"
    }
   ]
  },
  {
   "title": "Kubelet Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Errors / Hour" }
   ],
   "targets": [
    {
     "expr": "delta(kubelet_runtime_operations_errors_total[1h])\n",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  }
 ]
}