- name: set hostname from entry in hosts file
  hostname:
    name: "{{ inventory_hostname }}"

- name: copy inputrc to user directory
  copy:
    src: .inputrc
    dest: /home/ubuntu/.inputrc
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: copy inputrc to root directory
  copy:
    src: .inputrc
    dest: /root/.inputrc
    owner: root
    group: root
    mode: "0644" 

- name: Install required packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
      - curl
      - tar
      - unzip

- name: Update repositories cache
  apt:
    update_cache: yes

- name: pi-only tasks
  block:
  # This may not work on all devices
  # we should set this dynamically based on host level attributes
  - name: Set Overclock on PIs
    lineinfile:
      path: /boot/firmware/config.txt
      regexp: "^{{ item }}"
      line: "{{ item }}"
    loop:
      - over_voltage=6
      - arm_freq=2000
  - name: copy boot ops to enable cgroups
    copy:
      src: "{{ item }}"
      dest: "/boot/firmware/{{ item }}"
      owner: root
      group: root
      mode: "0644" 
    loop:
      - "{{ 'cmdline.txt' if ansible_distribution_major_version | int >= 20 else 'nobtcmd.txt'}}"
  when: ansible_architecture == "aarch64"

- name: Reboot and wait up to 5 minutes for the host to respond
  reboot:
    reboot_timeout: 300
